# These are supported funding model platforms
# Sources:
# https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository


community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
github: [yashbhutwala] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
issuehunt: # Replace with a single IssueHunt username
ko_fi: # Replace with a single Ko-fi username
liberapay: # Replace with a single Liberapay username
open_collective: # Replace with a single Open Collective username
otechie: # Replace with a single Otechie username
patreon: # Replace with a single Patreon username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
